[package]
name = "browser"
version = "0.1.0"
edition = "2021"

[dependencies]
# Servo dependencies will be added here
# For now, we'll start with a simple test program

[profile.release]
panic = "abort"
lto = true
opt-level = "z"  # Optimize for size

[lib]
crate-type = ["staticlib"]
